version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel
    depends_on:
      - app

  postgres:
    image: postgres:16-alpine
    container_name: laravel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-laravel}
      POSTGRES_USER: ${DB_USERNAME:-laravel}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

  redis:
    image: redis:7.4-alpine
    container_name: laravel_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - laravel

  minio:
    image: minio/minio:latest
    container_name: laravel_minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9002:9001"
    command: server /data --console-address ":9001"
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog:latest
    container_name: laravel_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel

  supervisor:
    build:
      context: .
      dockerfile: docker/supervisor/Dockerfile.simple
    container_name: laravel_supervisor
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./storage/logs:/var/www/storage/logs
    ports:
      - "9001:9001"
    networks:
      - laravel
    depends_on:
      - postgres
      - redis
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION}
      - CACHE_DRIVER=${CACHE_DRIVER}
      - SESSION_DRIVER=${SESSION_DRIVER}
      - DOCUMENT_ANALYSIS_QUEUE=${DOCUMENT_ANALYSIS_QUEUE}
      - DOCUMENT_PROCESSING_QUEUE=${DOCUMENT_PROCESSING_QUEUE}
      - ANALYSIS_JOB_MAX_TRIES=${ANALYSIS_JOB_MAX_TRIES}
      - ANALYSIS_JOB_TIMEOUT=${ANALYSIS_JOB_TIMEOUT}
      - ANALYSIS_JOB_RETRY_AFTER=${ANALYSIS_JOB_RETRY_AFTER}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - CLAUDE_DEFAULT_MODEL=${CLAUDE_DEFAULT_MODEL}
      - CLAUDE_MAX_TOKENS=${CLAUDE_MAX_TOKENS}
      - CLAUDE_TEMPERATURE=${CLAUDE_TEMPERATURE}
      - CLAUDE_TIMEOUT=${CLAUDE_TIMEOUT}
      - CLAUDE_MAX_RETRIES=${CLAUDE_MAX_RETRIES}
      - CLAUDE_RETRY_DELAY=${CLAUDE_RETRY_DELAY}

networks:
  laravel:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  minio_data: